version: '3'
services:
  mysql57:
      image: mysql:5.7
      restart: always
      ports:
          - 3336:3306
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--max_allowed_packet=2G', '--sql_mode=NO_ENGINE_SUBSTITUTION', '--init-file', '/data/application/init.sql']
      environment:
          MYSQL_ROOT_PASSWORD: root
      volumes:
          - ./mysql:/var/lib/mysql
          - ./init.sql:/data/application/init.sql
      networks:
          - directus

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:11
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - mysql57
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      EXTENSIONS_AUTO_RELOAD: 'true'

      DB_CLIENT: 'mysql'
      DB_HOST: 'mysql57'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'root'
      DB_PASSWORD: 'root'

      CACHE_ENABLED: 'true'

      REDIS_HOST: 'cache'
      REDIS_PORT: '6379'

      CACHE_STORE: 'redis'
      RATE_LIMITER_STORE: 'redis'
      SYNCHRONIZATION_STORE: 'redis'
      MESSENGER_STORE: 'redis'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      MARKETPLACE_TRUST: 'all'

      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:
