export enum ProgressTrackerId {
  PREPARING_IMPORT,
  RETRIEVING_LANGUAGES,
  IMPORT_FINISHED,
  FETCHING_CONTENT_FROM_LOCALAZY,
  EXPORT_FINISHED,
  LOADED_LOCALAZY_PROJECT,
  IMPORTED_CONTENT_CHUNK,
  UPDATING_DIRECTUS_COLLECTION,

  NOTHING_TO_IMPORT,
  NOT_CONNECTED_TO_LOCALAZY,
  UPDATING_DIRECTUS_COLLECTION_ERROR

}
