name: QA checks

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  check:
    name: Lint, format, test & build
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install deps
        run: npm ci

      - name: Set production config
        run: npm run set-production-config

      - name: Check (lint + format + test)
        run: npm run check

      - name: Build (production)
        run: npm run build
