name: QA checks

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  lint:
    name: Lint & build package
    runs-on: [ self-hosted, Linux ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install deps
        run: npm ci

      - name: Build & lint
        run: |
          npm run set-production-config
          npm run lint
          npm run build:development
