name: QA checks

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  check:
    name: Lint, format, test & build
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Set production config
        run: pnpm run set-production-config

      - name: Check (lint + format + typecheck + test)
        run: pnpm run check

      - name: Build (production)
        run: pnpm run build
